# -*- coding: utf-8 -*-
"""Day 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aBF0HhYck9aTDowYpO46Og2O2tfr7FN6
"""

from urllib.request import urlretrieve

import pandas as pd
iris = 'http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
urlretrieve(iris)
urlretrieve(iris)
df = pd.read_csv(iris, sep=',')
attributes = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]
df.columns = attributes
print(df.head())
df.info()

sampled_data = df.sample(n=30, random_state=42)

print("\nSampled Data (30 Observations):")
print(sampled_data)

import numpy as np
import matplotlib.pyplot as plt

sample_means = []

for _ in range(100):
    sample = df.sample(n=30, random_state=np.random.randint(0, 10000))
    sample_mean = sample["sepal_length"].mean()
    sample_means.append(sample_mean)

plt.figure(figsize=(10, 6))
plt.hist(sample_means, bins=10, color="skyblue", edgecolor="black", alpha=0.7)
plt.title("Distribution of Sample Means (Sepal Length)")
plt.xlabel("Sample Mean (Sepal Length)")
plt.ylabel("Frequency")
plt.axvline(np.mean(sample_means), color="red", linestyle="dashed", linewidth=2, label="Mean of Sample Means")
plt.legend()
plt.show()

