# -*- coding: utf-8 -*-
"""Day 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18GKouSLvgNM_rRscXS6lC6E5_CC32n4C
"""

import pandas as pd
import numpy as np
file_path = '/content/Fraudulent_E-Commerce_Transaction_Data.csv'
df = pd.read_csv(file_path)
df.head()

print(df.info())

numerical_columns = df.select_dtypes(include="number")
for column in numerical_columns:
    print(f"--- {column} ---")
    print(f"Mean: {df[column].mean()}")
    print(f"Median: {df[column].median()}")
    print(f"Mode: {df[column].mode().iloc[0]}")
    print("\n")

for column in numerical_columns:
    print(f"--- {column} ---")
    variance = df[column].var()
    std_dev = df[column].std()
    value_range = df[column].max() - df[column].min()

    print(f"Variance: {variance}")
    print(f"Standard Deviation: {std_dev}")
    print(f"Range: {value_range}")
    print('\n')

numerical_columns = df.select_dtypes(include="number").columns
print(f"Numerical columns: {numerical_columns}")

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10, 6))
sns.histplot(df[numerical_columns[0]], kde=True, color="blue")
plt.title(f"Distribution of {numerical_columns[0]}")
plt.xlabel(numerical_columns[0])
plt.ylabel("Frequency")
plt.show()

if len(numerical_columns) > 1:
    plt.figure(figsize=(10, 6))
    sns.scatterplot(x=df[numerical_columns[0]], y=df[numerical_columns[1]], hue=df[numerical_columns[0]])
    plt.title(f"Scatter Plot: {numerical_columns[0]} vs {numerical_columns[1]}")
    plt.xlabel(numerical_columns[0])
    plt.ylabel(numerical_columns[1])
    plt.show()