# -*- coding: utf-8 -*-
"""Day 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kn861v5KW6AYe-GsV-wjKRSmT4_nqtwD
"""

from urllib.request import urlretrieve
import pandas as pd
iris = 'http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
urlretrieve(iris)
urlretrieve(iris)
df = pd.read_csv(iris, sep=',')
attributes = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]
df.columns = attributes
print(df.head())
df.info()

import pandas as pd
from scipy.stats import ttest_ind

# Load the dataset
iris = 'http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
attributes = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]
df = pd.read_csv(iris, sep=',', header=None, names=attributes)




setosa_petal_length = df[df['class'] == 'Iris-setosa']['petal_length']
versicolor_petal_length = df[df['class'] == 'Iris-versicolor']['petal_length']

# Perform the independent t-test
t_stat, p_value = ttest_ind(setosa_petal_length, versicolor_petal_length)

# Output the t-test results
print(f"T-statistic: {t_stat}")
print(f"P-value: {p_value}")

# Interpretation of the results
alpha = 0.05  # Significance level
if p_value < alpha:
    print("Reject the null hypothesis: The means of petal lengths are significantly different.")
else:
    print("Fail to reject the null hypothesis: The means of petal lengths are not significantly different.")